DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS personalDB;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE personalDB (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  document_type CHAR NOT NULL,
  document_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL
);
